version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nextgenCTI"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5t5rudn6zu6h"
s3_prefix = "nextgenCTI"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"

